baseURL = "/"
languageCode = "en-us"
title = "AnsiMail @ bsd.ac"
theme = "learn"

# needed for ox-hugo code snippets
[markup.goldmark.renderer]
unsafe = true

# learn theme specific parameters

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "ansimail"
desc = "Fullstack, security focused mailserver based on OpenSMTPD for OpenBSD using ansible"
