baseURL = "https://ansimail.bsd.ac/"
languageCode = "en-us"
title = "AnsiMail @ bsd.ac"
theme = "book"

# book theme parameters
enableGitInfo = true

[menu]
[[menu.after]]
name = "Github"
url = "https://github.com/AnsiMail/AnsiMail"
weight = 10

[params]
  #BookLogo = 'logo.png'

  BookSection = '*'

  BookRepo = 'https://github.com/AnsiMail/ansimail.bsd.ac'

  BookSearch = true

  BookComments = false
